# Generated by Django 2.0.1 on 2018-01-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings_text', models.CharField(max_length=50)),
                ('description_text', models.CharField(max_length=500)),
            ],
        ),
    ]
