# Generated by Django 2.0.1 on 2018-01-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180108_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/recommendation')),
                ('recommendation_name', models.CharField(max_length=60)),
                ('recommendation_company', models.CharField(max_length=40)),
                ('recommendation_text', models.CharField(max_length=300)),
            ],
        ),
    ]
