# Generated by Django 2.0.1 on 2018-01-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20180114_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
