# Generated by Django 2.0.1 on 2018-01-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20180115_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
