# Generated by Django 2.0.1 on 2018-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20180115_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description_text',
            field=models.TextField(),
        ),
    ]
