# Generated by Django 2.0.1 on 2018-01-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20180116_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/art_thumbs'),
        ),
    ]
