# Generated by Django 2.0.1 on 2018-01-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_art_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='image',
            field=models.ImageField(upload_to='images/art/'),
        ),
    ]
